### ISSUE TITLE
does this module belong here?

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.web#2]
on September 4th 2015 @brettatoms wrote to @mfrasca:
> As far as I’m concerned you pretty much own the project now and whatever you decide is fine by me. 

Now I'm a bit concerned with possible future confusion (to current @RoDuth etc and perspective @tmyersdn etc users) deriving from a module named `bauble.web`, not containing any of my contributions and with unclear unstated goals. As far as I'm concerned, I am already presenting '[ghini](http://github.com/mfrasca/ghini/)' as the (a future, in a future) web interface to bauble.classic, and I am not calling it 'bauble' because it's still too much of a prototype to be included in the Bauble project.

I think that since you Brett made sure the module does not in any way belong to me, then I think it also does not belong here.

**Comment by brettatoms** [comment]
I really don't know how to respond to this.  There's so much wrong with this perspective that I don't know where to start...but I'll do my best.

1. Why can't this GH organization be a place for experimentation, new ideas and innovation?  

2. Does the existence of this repo really cause mass confusion?  I don't remember anyone asking me to clear up any confusion with this repo.

3. I remember reaching out to you on a number of occasions with long and extensive emails to try to get you involved in the a web version of Bauble when I was first working in it 2(?) years ago.  Communication was inconsistent at best so I gave up.

4. Is a GH issue really the best place to have this conversation?

5. Why merge fixes into an experimental repo?  The ideas that I've been working on in this repo are independent of bauble.classic and if/when I feel like this repo is in a good position then I'll happily merge any change in at all?  I mean have you seen the code in this repo, its a fucking nightmare.  Merging in changes from bauble.classic would be pointless at this stage.  And yes, I was planning on relicensing this repo as GPL to make sure merges were possible.

5. I welcome any and all collaboration on this repo.  

6.  By handing over the reins to bauble.classic I thought I was doing something good and that would be good for anyone out there still using bauble.  I took down the web page for bauble.web that I built so it could be replace by one that represented bauble.classic.  I offered to rename the bauble.classic repo to bauble to make sure it was considered the main project in this GH organization.  I pay for the bauble.io domain out of my pocket.  I spent 8 years of my life working on Bauble by myself with no other help other than translations.  Now here we are not a year after completely handing over the reins to bauble.classic and I get this issue telling me my ideas and experiments aren't welcome?

7.  In what way did I make "sure the module does not belong in any way to [you]".  You are an administrator to this GH organization.  You have full rights to commit to this repo, create pull requests, create issues (obviously), etc.   I even risked being completely deleted from this organization by making you an Owner.


I really don't know what prompted this issue.  If I hurt your feelings somewhere along the way then I'm sorry. Really.  But this kind of shit is unnecessary.

**Comment by mfrasca** [comment]
Brett, I'm sorry if it got to you this hard, it was not my intention. I am used to working issue-based, first I state what I'm about to do, then I do it. and I'm prefer to develop code test-driven, otherwise I do not manage to follow what I'm doing myself, let alone what someone else does. I'm not concerned with you experimenting whatever you feel like experimenting, but just please not under the name "bauble.web", in particular standing what you write in 5.
to number 8: you rolled back all that I had done to Bauble in the latest years. this thing you're doing here effectively "does not belong in any way to me". I just fail to follow it.

**Comment by mfrasca** [comment]
>  I pay for the bauble.io domain out of my pocket

I was not aware of this and should have asked. what do you suggest we do? I'm fine with both falling back to bauble.github.io as well as with contributing (up to 100%) to the expenses of keeping the domain.

**Comment by brettatoms** [comment]
When I started this repo (which was a combination of bauble.api and bauble.webapp) it was before you had made any changes to Bauble.  There's was no rolling back, the changes didn't yet exist.  

> I was not aware of this and should have asked. what do you suggest we do? I'm fine with both falling back to bauble.github.io as well as with contributing (up to 100%) to the expenses of keeping the domain.

I don't care about paying for the domain.  The point is that I still consider myself an active member of this organization and community.
